#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your
# load-balancer IP (lb-01). Let’s also add other subdomains to make our
# life easier, and write a Bash script that will display information
# about subdomains.

domains () {
	if [[ "$#" -ne "2" ]]
	then
		dig web-01."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{split($0,args," "); printf ("The subdomain web-01 is a %s record and points to %s\n"), args[4], args[5]}'
		dig www."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{split($0,args," "); printf ("The subdomain www is a %s record and points to %s\n"), args[4], args[5]}'
		dig web-02."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{split($0,args," "); printf ("The subdomain web-02 is a %s record and points to %s\n"), args[4], args[5]}'
		dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{split($0,args," "); printf ("The subdomain lb-01 is a %s record and points to %s\n"), args[4], args[5]}'
	else
		dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v var="$2" '{split($0,args," "); printf "The subdomain %s is a %s record and points to %s\n", var, args[4], args[5]}'
	fi
}
domains "$1" "$2"
