#!/usr/bin/env bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

name=$(date '+%Y-%m-%d')
sudo mysqldump -u root -p$1 --all-databases --master-data > backup.sql
sudo tar -zcvf "$name.tar.gz" backup.sql
