#!/usr/bin/ev bash
# Write a Bash script that generates a MySQL dump and creates a compressed archive out of it.

name=${date +'%d/%m/%Y'}
mysqldump -u root -p --all-databases --master-data > backup.sql
tar -vcfz name.tar.gz backup.sql
mysql -p"${PASS}"