#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu sandbox’s
# Nginx installation from listening on port 80. Feel free to install whatever
# tool you need, start and destroy as many sandboxes as you need to debug the
# issue. Then, write a Bash script with the minimum number of commands to 
# automate your fix.

new_string="listen 80 default_server;\nlisten [::]:80 default_server;"
sudo chmod 777 /etc/nginx/sites-enabled/default
sudo sed -i "s/listen 8080 default_server;\nlisten [::]:8080 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
