#!/usr/bin/env bash
# script que imprime 10 veces usando if la frase "Best School"
# y en la novena iteracion imprime "Hi"

i=1
while ((i <= 20))
do
    case $i in
    4) echo "bad luck from China" ;;
    9) echo "bad luck from Japan" ;;
    17) echo "bad luck from Italy" ;;
    esac
    ((i++))
done